server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-app
    username: postgres
    password: postgrespass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
